settings:

  subjects:

    Ph:
      name: Фізика та астрономія
      link: https://meet.google.com/vxn-vtwy-ndi

    I:
      name: Інформатика
      link: https://meet.google.com/nrh-dhdg-myo

    M:
      name: Математика
      link: https://meet.google.com/qki-umti-riq

    FLi:
      name: Зарубіжна література
      link: https://meet.google.com/hgv-offr-yvb

    PE:
      name: Фізична культура
      link: https://meet.google.com/vwy-dswx-ehy

    DoU:
      name: Захист України
      link: https://meet.google.com/vwy-dswx-ehy

    DoU2:
      name: Захист України (МП)
      link: https://meet.google.com/bxs-wvbg-nxu

    H:
      name: "Історія: Україна і світ"
      link: https://meet.google.com/cws-hhzu-nez

    ULi:
      name: Українська література
      link: https://meet.google.com/sxu-otmd-nwt

    ULa:
      name: Українська мова
      link: https://meet.google.com/mck-vpyc-wyk

    Ch:
      name: Хімія
      link: https://meet.google.com/cnj-owwi-eyc

    FLa:
      name: Іноземна мова
      link: https://meet.google.com/mrv-vqjb-csy

    G:
      name: Географія
      link: https://meet.google.com/xfi-zkba-mco

    B:
      name: Біологія і екологія
      link: https://meet.google.com/sfc-tgbt-roc

  schedule:
    - # Week 1
      - [ B, Ph, H, PE ]       # Mon
      - [ Ch, DoU, ULa, DoU2 ] # Tue
      - [ None, FLa, FLi ]     # Wen
      - [ B, I, G ]            # Thu
      - [ I, ULi, M ]          # Fri
    - # Week 2
      - [ Ch, Ph, H, PE ]      # Mon
      - [ Ch, DoU, ULa ]       # Tue
      - [ H, FLa, FLi ]        # Wen
      - [ B, I, G ]            # Thu
      - [ I, ULi, M ]          # Fri

  academic_context:
    reference_date: "2026-01-12"
    reference_week: 2

  time:
    - "08:30 – 09:50"
    - "10:00 – 11:20"
    - "11:35 – 12:55"
    - "13:10 – 14:30"
    - "14:40 – 16:00"

  admins:
    - 814528657
    - 6133407632