# Before using this file in project, rename it:
#  COPY HERE -->> config.yaml <<-- COPY HERE

settings:

  subjects:

    # The "None" key is not working !!! This is reserved key for void in subjects

    Ph:
      name: Physics
      link: https://meet.google.com
    B:
      name: Biology
      link: https://meet.github.com


  schedule:

    - # Week
      - # Day
        - B # Subject
        - Ph
        - None # A None string will be skipped
        - B
        # ...
      # ...
    # ...

    # or like this:
    -
      - ["B", "Ph", None, "B"]

  academic_context:
    reference_date: "2026-01-12" # YYYY-MM-DD | what day the school year began
    reference_week: 2 # what week the school year began

  time:
    - "08:30 – 09:50" # lessons' schedule
    - "10:00 – 11:20"
    - "11:35 – 12:55"
    - "13:10 – 14:30"
    - "14:40 – 16:00"

  admins:
    - 123456789 # telegram id (retrieve it in @myTelegramChatIdBot)